---
# Installation
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

# Distribution Tasks
## Install openbox

# Common Tasks
- name: Copy .xinitrc file
  template:
    src: xinitrc.j2
    dest: "{{ user_home }}/.xinitrc"
