---
- name: Update System
  become: true
  pacman:
    update_cache: yes
    upgrade: yes

- name: Install yay
  become: true
  pacman:
    name: yay
    state: present

- name: Create Ansible User
  user:
    name: ansible
    group: wheel

- name: Add ansible user to sudoers
  lineinfile:
    path: /etc/sudoers.d/11-install-ansible
    line: 'ansible ALL=(ALL) NOPASSWD: /usr/bin/pacman'
    create: yes
