---
- name: Install DNF Plugins
  become: true
  dnf:
    name: dnf-plugins-core
    state: present

- name: Install Docker Repository
  become: true
  # warn: false
  command: dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo

- name: Update Packages Cache
  become: true
  dnf:
    update_cache: true

- name: Install Docker
  become: true
  dnf:
    name:
      - "docker-ce"
      - "docker-ce-cli"
      - "containerd.io"
      - "grubby"
    state: present

- name: Enable Cgroups
  become: true
  command: grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"

- name: restart host
  reboot:
    reboot_timeout: 120