---
# Installation
- import_tasks: debian.yml
  when: ansible_os_family == "Debian"
- import_tasks: redhat.yml
  when: ansible_os_family == "RedHat"
- import_tasks: arch.yml
  when: ansible_os_family == "Archlinux"

# Distribution Tasks
## Install VIM

# Common Tasks
- name: Copy .vimrc file
  template:
    src: vimrc.j2
    dest: "{{ user_home }}/.vimrc"

